### ISSUE TITLE
German Translation wrong gender

### ISSUE THREAD

**Issue by Expakun** [Moffein/HereticMod#10]
The Gender of the Heretic is Wrong in the Achievement description in the German translation.

It says "Entkomme vom Mond als der geheimnisvolle Überlebende." but it should be "Entkomme vom Mond als die geheimnisvolle Überlebende."

**Comment by Moffein** [comment]
Thanks for the feedback, will fix this.

**Comment by Moffein** [comment]
https://github.com/Moffein/HereticMod/blob/master/language/de-DE/HereticMod.txt
Are there any other places where this needs to be changed?

**Comment by Expakun** [comment]
> https://github.com/Moffein/HereticMod/blob/master/language/de-DE/HereticMod.txt Are there any other places where this needs to be changed?

No the rest is correct

**Comment by Moffein** [comment]
Alright, uploaded!
