### ISSUE TITLE
uh translate

### ISSUE THREAD

**Issue by Drochuagon** [Moffein/HereticMod#6]
hio idk how to request my translation sooooooooo
its here, Russian language ye ye from me (very cool purple furry dragon)
thx!
[HereticMod.txt](https://github.com/Moffein/HereticMod/files/10097305/HereticMod.txt)

**Comment by Moffein** [comment]
Adding this, thanks!

**Comment by Drochuagon** [comment]
hioooooooooo again 
i messed up with 1 letter so here is updated trans
[HereticMod.txt](https://github.com/Moffein/HereticMod/files/10099179/HereticMod.txt)
 also passive ability called "Nevermore@ is translated as "никогда больше" - thats wrong, good translate is "Невермор". (idk how to suggest it in txt file so say this here sry)

**Comment by Moffein** [comment]
Uploading this.
Passive ability and other abilities use the game's default translations, so they can't be changed.
The reason the Secondary/Special skills have an entry in the file is because the English verison of them has improper styling.

**Comment by Drochuagon** [comment]
oh, thx for the answer! and for accepting my translation too <З

**Comment by Drochuagon** [comment]
hello again! I've just look at russian trnslate and notice that translate mistake still here :D looks like You are upload the otld file)))

**Comment by Moffein** [comment]
Just to confirm, could you upload the latest translation file here? I've checked, and the one included with the mod is the one from this post.

> hioooooooooo again i messed up with 1 letter so here is updated trans [HereticMod.txt](https://github.com/Moffein/HereticMod/files/10099179/HereticMod.txt) also passive ability called "Nevermore" is translated as "никогда больше" - thats wrong, good translate is "Невермор". (idk how to suggest it in txt file so say this here sry)

**Comment by Drochuagon** [comment]
[HereticMod1.txt](https://github.com/Moffein/HereticMod/files/10149563/HereticMod1.txt)
add 1 for sure

**Comment by Moffein** [comment]
Uploaded the fix.
